name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK master'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: bastardkb/bastardkb-qmk
      qmk_ref: bkb-master
      preparation_command: |
        mv qmk.json qmk-main.json && mv qmk-bastardkb.json qmk.json

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: [build]
