name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    with:
      qmk_repo: holykeebs/qmk_firmware
    #   qmk_ref: c10fa28257f0459cfee2565fee78ed0d07206bf9
      qmk_ref: hk-master

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    if: always() && !cancelled()
    needs: build
